### PR TITLE
Multi pipeline

### PR DESCRIPTION
**Pull request by laszlocph**

### CODE REVIEW

**Comment by AkiraNorthstar** [comment]
Hi Laszlo!
I read your changes - it's exciting!
Will you also implement this feature for other remotes, such as gitea?

**Comment by laszlocph** [comment]
Not in the first go. There is one thing needed to make it work with other remotes. Implementing this function: https://github.com/laszlocph/drone-oss-08/pull/32/files#diff-499f2a70701091061ee2b89aef2dcf28R253

I probably try to get away with creating a follow up ticket with a "Good first issue" tag.

It's probably 2 hours of work, so I may end up doing it, but probably a month later. Will see.

**Comment by laszlocph** [comment]
Documentation: https://github.com/laszlocph/docs/blob/master/content/usage/concepts/multi-pipeline.md

**Comment by laszlocph** [comment]
#10

**Pull request merged**
